// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZEA_p26H_ZuIVefLEq2tiEMrZcXJm_l0',
    appId: '1:557104698505:web:b2ade84eb7202ed303e258',
    messagingSenderId: '557104698505',
    projectId: 'trendhive-ed9b8',
    authDomain: 'trendhive-ed9b8.firebaseapp.com',
    storageBucket: 'trendhive-ed9b8.firebasestorage.app',
    measurementId: 'G-XLL79SH94B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJwAM4YaaprJYQr0IbN0O8yHSlsCrUXE',
    appId: '1:557104698505:android:acec890f547c8eca03e258',
    messagingSenderId: '557104698505',
    projectId: 'trendhive-ed9b8',
    storageBucket: 'trendhive-ed9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCY71rypRoXjAzjT6J4tBkOlHmUAkd7Ik',
    appId: '1:557104698505:ios:8db002022d11800403e258',
    messagingSenderId: '557104698505',
    projectId: 'trendhive-ed9b8',
    storageBucket: 'trendhive-ed9b8.firebasestorage.app',
    iosBundleId: 'com.alphafour.trendhive.trendhive',
  );

}